### ISSUE TITLE
New Collector Role

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/documentation-wiki#107]
Issue Documentation is http://handbook.arctosdb.org/how_to/How-to-Use-Issues-in-Arctos.html

**Table**
[Collector_role](http://arctos.database.museum/info/ctDocumentation.cfm?table=CTCOLLECTOR_ROLE)

**Value**
donor

**Definition**
Agent who gave the object to the collection. May or may not be the same person who collected the object.

**Collection type**
N/A

**Attribute data type**
controlled text

**Attribute value**
Agents

**Attribute units**
N/A

**Part tissue flag**
N/A

**Other ID BaseURL**
N/A

**Context**
The donor and collector may be two different people and I would like to be able to distinguish them.

**Priority**
I would like to have this resolved by date: 2018/12/10

**Comment by campmlc** [comment]
What Angie is doing:

donor field in specimen record to acknowledge donors who may wish to have
their
name publicly associated with the item.

We handle this by listing the donor as the last collector in the string, if
they're not the original collector.

Would not be obvious to anyone outside of her collection management
environment. We want to encourage donors and be able to be responsive to
those who wish to be publicly acknowledged. Putting the info into the
accession is useful for curation, but not for public acknowledgment. Use of
the latter would be a conscious choice by the cm to use during data entry,
a separate process in time, space, and staffing from accessioning.

**Comment by campmlc** [comment]
This sounds interesting:
we can pull accession stuff into the specimen record if that's the problem.
Can we add a question to the accession record that asks if donor name
should be made public, and if so, it will autodisplay as "donor" on the
specimen record?

**Comment by AJLinn** [comment]
> Especially for an art collection that might want to highlight a donor's name (just thinking ahead - we could use an art collection....).

I'd say about 80-90% of my collection have "gift" (i.e., donation) as the mode of acquisition. We are beginning to examine the possibility of making all of our accession records publicly accessible, due to the desire for transparency, research value, and acknowledging the sometimes complicated credit lines associated with donations. I will continue to support Dusty's position that donor recognition happens at the accession level, not the individual object level, unless it's in an exhibit label. The accession info helps to contextualize the "received by" vs. the "credit line," which might involve something like "This object donated in honor of Mrs. Sally Smith" someone who is neither the legal donor nor a collector, just someone the family wanted to honor with the donation. Auto-recognition doesn't provide any explanation about this type of credit, which happens infrequently but does happen enough that it would create confusion and incorrect information to someone searching. 

If a single item within a larger accession was donated by a different person, a simple statement in the remarks fields clearly acknowledges that role.

**Comment by campmlc** [comment]
I think the issue should be whether there is greater risk of  loss of data
and discoverability through limiting agent roles, or through expanding
them. If adding an agent role helps reduce data loss and increase
discoverability, then we should add it, and vice versa if not.

**Comment by marecaguthrie** [comment]
All of the events that happened in the object record happened to the object. I don't understand your suggestion, Dusty. Can you elaborate further? 

Is it possible to link an agent to an event and specify their role in the event?

Person A took a photograph
Person B printed the photograph
Gallery C sold the photograph by Person A to person D
Person D died and left the photo to Person E
Person E donated the photograph to Museum F
Museum F sold the photo to Museum G
Conservator H repaired the photograph

**Comment by Jegelewicz** [comment]
I don't know what needs documenting here.
