### ISSUE TITLE
Duplication in Accession How-Tos

### ISSUE THREAD

**Issue by Jegelewicz** [ArctosDB/documentation-wiki#93]
We currently have two "How To Create an Accession" how tos:

[How to Create an Accession](http://handbook.arctosdb.org/how_to/How-to-Create-an-Accession.html)

and

[How to Create and Edit an Accession](http://handbook.arctosdb.org/how_to/How-to-Create-Edit-an-Accession.html)

As far as I can tell, the "create" part in both of these is the same. Can we either get rid of the first one or change the second one to "How to Manage Accessions" and remove the create part from it?
@mkoo and @ebraker you guys are authors - what do you think?

**Comment by Jegelewicz** [comment]
Once we have this resolved return to #92

**Comment by ebraker** [comment]
Thanks Teresa. I just went in there and actually deleted "How to Create and Edit an Accession" because the last part on managing/batch editing accessions is already pulled out as its own How-To (exact duplicate):
[How to Batch Update Accessions](http://handbook.arctosdb.org/how_to/How-to-Batch-Update-Accessions.html)

Thus, I left [How to Create An Accession](http://handbook.arctosdb.org/how_to/How-to-Create-an-Accession.html) as is.

**Comment by ebraker** [comment]
...though I just noticed that the [batch update accessions  how-to](https://github.com/ArctosDB/documentation-wiki/blob/gh-pages/_how_to/How-to-Batch-Update-Accessions.markdown) in github includes screenshots, but when routed through arctosdb.org, it does not include [any](http://handbook.arctosdb.org/how_to/How-to-Batch-Update-Accessions.html)

**Comment by Jegelewicz** [comment]
@ebraker thanks! I'll check that out when I make the edits I have for the create accessions how to.

**Comment by Jegelewicz** [comment]
I think the accessions how tos are good now.
